### ISSUE TITLE
contact map生成

### ISSUE THREAD

**Issue by GeniusYx** [xzenglab/TAGPPI#1]
作者，您好，感谢您开源代码，在文中的Construction of predicted contact map这一节您说明了contact map的生成规则，请问您可以告诉我生成contact map的具体代码吗？我在https://alphafold.ebi.ac.uk/download下载了数据，但是解压之后是pdb文件，请问我是需要对这个数据进行处理然后生成您提供的数据中npz文件吗？

如果不能告知处理细节，请问您可以告诉我能参考什么代码吗？

十分感谢～打扰了

**Comment by wenkaiyan-kevin** [comment]
你好@[GeniusYx](https://github.com/GeniusYx)
请问你的问题解决了吗？如果解决了，恳请指教

**Comment by FYY99117** [comment]
请问你的问题解决了吗？如果解决了，恳请指教

**Comment by xzenglab** [comment]
> 作者，您好，感谢您开源代码，在文中的Construction of predicted contact map这一节您说明了contact map的生成规则，请问您可以告诉我生成contact map的具体代码吗？我在[https://alphafold.ebi.ac.uk/download下载了数据，但是解压之后是pdb文件，请问我是需要对这个数据进行处理然后生成您提供的数据中npz文件吗？](https://alphafold.ebi.ac.uk/download%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BD%86%E6%98%AF%E8%A7%A3%E5%8E%8B%E4%B9%8B%E5%90%8E%E6%98%AFpdb%E6%96%87%E4%BB%B6%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E6%98%AF%E9%9C%80%E8%A6%81%E5%AF%B9%E8%BF%99%E4%B8%AA%E6%95%B0%E6%8D%AE%E8%BF%9B%E8%A1%8C%E5%A4%84%E7%90%86%E7%84%B6%E5%90%8E%E7%94%9F%E6%88%90%E6%82%A8%E6%8F%90%E4%BE%9B%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%ADnpz%E6%96%87%E4%BB%B6%E5%90%97%EF%BC%9F)
> 
> 如果不能告知处理细节，请问您可以告诉我能参考什么代码吗？
> 
> 十分感谢～打扰了

可参考代码map.py
