### ISSUE TITLE
在运行代码过程中遇到的一个问题

### ISSUE THREAD

**Issue by 852jjj** [xzenglab/TAGPPI#3]
老师，您好，最近在研究生物信息学领域读到了您的论文，深受启发。我想要进行一些实验加深对文章的理解，但是在编译的时候遇到了如下问题：
dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device.
代码定位在如下位置：
File "/TAGPPI-main/my_train_and_validation.py", line 57, in train
    y_pred = attention_model(dgl.batch(G1),pad_dmap(dmap1),dgl.batch(G2), pad_dmap(dmap2))
我根据它定位的语句修改了attention_model这个模型对应的forward函数里的加法操作。修改的语句如下：
      gc1=torch.add((1-w1)*g1,w1*seq1)和 gc2=torch.add((1-w1)*g2,w1*seq2)
修改后的语句为：
        y1=(1-w1)*g1
        y2=w1*seq1
        gc1 = torch.add(y1.to('cpu'),y2.to('cpu'))
        x1=(1-w1)*g2
        x2=w1*seq2
        gc2=torch.add(x1.to('cpu'),x2.to('cpu')
再次运行代码还是会出现如下问题：
dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device.
我不知道它是因为什么原因引起的，不知您是否可以解答我的困惑。谢谢！

**Comment by tianyn19** [comment]
> 老师，您好，最近在研究生物信息学领域读到了您的论文，深受启发。我想要进行一些实验加深对文章的理解，但是在编译的时候遇到了如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 代码定位在如下位置： File "/TAGPPI-main/my_train_and_validation.py", line 57, in train y_pred = attention_model(dgl.batch(G1),pad_dmap(dmap1),dgl.batch(G2), pad_dmap(dmap2)) 我根据它定位的语句修改了attention_model这个模型对应的forward函数里的加法操作。修改的语句如下： gc1=torch.add((1-w1)_g1,w1_seq1)和 gc2=torch.add((1-w1)_g2,w1_seq2) 修改后的语句为： y1=(1-w1)_g1 y2=w1_seq1 gc1 = torch.add(y1.to('cpu'),y2.to('cpu')) x1=(1-w1)_g2 x2=w1_seq2 gc2=torch.add(x1.to('cpu'),x2.to('cpu') 再次运行代码还是会出现如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 我不知道它是因为什么原因引起的，不知您是否可以解答我的困惑。谢谢！

请问您一开始的protein_embeddings.npz文件怎么得到的呀？

**Comment by Yanara-Tian** [comment]
> 老师，您好，最近在研究生物信息学领域读到了您的论文，深受启发。我想要进行一些实验加深对文章的理解，但是在编译的时候遇到了如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 代码定位在如下位置： File "/TAGPPI-main/my_train_and_validation.py", line 57, in train y_pred = attention_model(dgl.batch(G1),pad_dmap(dmap1),dgl.batch(G2), pad_dmap(dmap2)) 我根据它定位的语句修改了attention_model这个模型对应的forward函数里的加法操作。修改的语句如下： gc1=torch.add((1-w1)_g1,w1_seq1)和 gc2=torch.add((1-w1)_g2,w1_seq2) 修改后的语句为： y1=(1-w1)_g1 y2=w1_seq1 gc1 = torch.add(y1.to('cpu'),y2.to('cpu')) x1=(1-w1)_g2 x2=w1_seq2 gc2=torch.add(x1.to('cpu'),x2.to('cpu') 再次运行代码还是会出现如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 我不知道它是因为什么原因引起的，不知您是否可以解答我的困惑。谢谢！

请问您一开始的protein_embeddings.npz文件是怎么得到的呀？通过seqVec对protein.dictonary.tsv直接处理得到的吗？

**Comment by 852jjj** [comment]
老师好，我是通过seqVec对protein.dictonary.tsv直接处理得到的，现在这个问题已经得到解决，感谢您的回答！




?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xzenglab/TAGPPI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xzenglab/TAGPPI] 在运行代码过程中遇到的一个问题 (Issue #3)





  
老师，您好，最近在研究生物信息学领域读到了您的论文，深受启发。我想要进行一些实验加深对文章的理解，但是在编译的时候遇到了如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 代码定位在如下位置： File "/TAGPPI-main/my_train_and_validation.py", line 57, in train y_pred = attention_model(dgl.batch(G1),pad_dmap(dmap1),dgl.batch(G2), pad_dmap(dmap2)) 我根据它定位的语句修改了attention_model这个模型对应的forward函数里的加法操作。修改的语句如下： gc1=torch.add((1-w1)_g1,w1_seq1)和 gc2=torch.add((1-w1)_g2,w1_seq2) 修改后的语句为： y1=(1-w1)_g1 y2=w1_seq1 gc1 = torch.add(y1.to('cpu'),y2.to('cpu')) x1=(1-w1)_g2 x2=w1_seq2 gc2=torch.add(x1.to('cpu'),x2.to('cpu') 再次运行代码还是会出现如下问题： dgl._ffi.base.DGLError: [12:07:26] /opt/dgl/src/array/array_arith.cc:81: Operator Add does not support cuda device. 我不知道它是因为什么原因引起的，不知您是否可以解答我的困惑。谢谢！
  
请问您一开始的protein_embeddings.npz文件是怎么得到的呀？通过seqVec对protein.dictonary.tsv直接处理得到的吗？

**Comment by ranzhran** [comment]
请问怎么直接通过seqVec对protein.dictonary.tsv处理得到呢，tsv怎么转换为对应的fasta格式呢
